name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      # issues with ubuntu:24.04:
      # W: binfmt_misc not found in /proc/mounts -- not mounted?
      # W: cannot find update-binfmts
      # E: arm64 can neither be executed natively nor via qemu user emulation with binfmt_misc
      image: ubuntu:22.04
      options: --privileged
      env:
        PIP_BREAK_SYSTEM_PACKAGES: 1
        DEBIAN_FRONTEND: noninteractive

    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [jammy, noble]
        libcamera_version: ["package-xml-0.1", "package-xml-0.3"]
        bloom_branch: ["meson", "meson-strip"]
        target_arch: [amd64, arm64]
        include:
        - ubuntu_version: jammy
          ros_version: humble
        - ubuntu_version: noble
          ros_version: jazzy
        exclude:
        - # ERROR: Meson version is 0.61.2 but project requires >= 0.63
          ubuntu_version: jammy
          libcamera_version: package-xml-0.3
        - # ModuleNotFoundError: No module named 'imp'
          ubuntu_version: noble
          libcamera_version: package-xml-0.1

    steps:
      - run: apt update

      - name: install sudo
        run: |
          apt install -y sudo

      - name: install bloom (meson)
        run: |
          apt install -y python3-pip git
          pip install git+https://github.com/christianrauch/bloom.git@${{ matrix.bloom_branch }}

      - name: generate repos file
        run: |
          cat << EOF > sources.repos
          repositories:
            src/libcamera:
              type: git
              url: https://github.com/christianrauch/libcamera.git
              version: ${{ matrix.libcamera_version }}
          EOF

      - run: usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $(whoami)

      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: ${{ matrix.ubuntu_version }}
          DEB_ARCH: ${{ matrix.target_arch }}
          ROS_DISTRO: ${{ matrix.ros_version }}
          SKIP_CHECKOUT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES_BRANCH: "${{ matrix.ubuntu_version }}-${{ matrix.ros_version }}-${{ matrix.target_arch }}-${{ matrix.libcamera_version }}-${{ matrix.bloom_branch }}"
