name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      # issues with ubuntu:24.04:
      # W: binfmt_misc not found in /proc/mounts -- not mounted?
      # W: cannot find update-binfmts
      # E: arm64 can neither be executed natively nor via qemu user emulation with binfmt_misc
      image: ubuntu:22.04
      options: --privileged
      env:
        PIP_BREAK_SYSTEM_PACKAGES: 1
        DEBIAN_FRONTEND: noninteractive

    strategy:
      fail-fast: false
      matrix:
        # jammy / package-xml-0.3:
        # ERROR: Meson version is 0.61.2 but project requires >= 0.63
        # noble / package-xml-0.1:
        # ModuleNotFoundError: No module named 'imp'
        version:
          - {ubuntu: noble,   ros: jazzy,   libcamera: package-xml}
        bloom_branch: ["meson_wrap_mode"]
        target_arch: [amd64, arm64]

    steps:
      - run: apt update

      - name: install sudo
        run: |
          apt install -y sudo

      - name: install bloom (meson)
        run: |
          apt install -y python3-pip git
          pip install git+https://github.com/christianrauch/bloom.git@${{ matrix.bloom_branch }}

      - name: generate repos file
        run: |
          cat << EOF > sources.repos
          repositories:
            src/libcamera:
              type: git
              url: https://github.com/christianrauch/libcamera-raspberrypi.git
              version: ${{ matrix.version.libcamera }}
          EOF

      - run: usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $(whoami)

      - uses: christianrauch/ros-deb-builder-action@network
        with:
          DEB_DISTRO: ${{ matrix.version.ubuntu }}
          DEB_ARCH: ${{ matrix.target_arch }}
          ROS_DISTRO: ${{ matrix.version.ros }}
          SKIP_CHECKOUT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES_BRANCH: "${{ matrix.version.ubuntu }}-${{ matrix.version.ros }}-${{ matrix.target_arch }}-${{ matrix.version.libcamera }}-${{ matrix.bloom_branch }}"
