name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04
      options: --privileged
      env:
        PIP_BREAK_SYSTEM_PACKAGES: 1
        DEBIAN_FRONTEND: noninteractive

    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [noble]
        target_arch: [amd64, arm64]
        include:
        - ubuntu_version: noble
          ros_version: jazzy

    steps:
      - run: apt update

      - name: install sudo
        run: |
          apt install -y sudo

      - name: install bloom
        run: |
          apt install -y python3-pip git
          apt install -y python3-bloom

      - name: generate repos file
        run: |
          cat << EOF > sources.repos
          repositories:
            src/camera_ros:
              type: git
              url: https://github.com/christianrauch/camera_ros.git
              version: main
          EOF

      - run: usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $(whoami)

      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: ${{ matrix.ubuntu_version }}
          DEB_ARCH: ${{ matrix.target_arch }}
          ROS_DISTRO: ${{ matrix.ros_version }}
          SKIP_CHECKOUT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES_BRANCH: "${{ matrix.ubuntu_version }}-${{ matrix.ros_version }}-${{ matrix.target_arch }}-main"
