name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      PIP_BREAK_SYSTEM_PACKAGES: 1
      DEBIAN_FRONTEND: noninteractive

    strategy:
      fail-fast: false
      matrix:
        # jammy / package-xml-0.3:
        # ERROR: Meson version is 0.61.2 but project requires >= 0.63
        # noble / package-xml-0.1:
        # ModuleNotFoundError: No module named 'imp'
        version:
          - {ubuntu: noble,   ros: jazzy,   libcamera: package-xml}
        bloom_branch: ["meson_wrap_mode"]
        target_arch: [amd64, arm64]

    steps:
      - run: sudo apt update

      - name: install bloom (meson)
        run: |
          sudo apt install -y python3-pip git
          pip install git+https://github.com/christianrauch/bloom.git@${{ matrix.bloom_branch }}

      - name: generate repos file
        run: |
          mkdir repo
          cat << EOF > repo/sources.repos
          repositories:
            src/libcamera:
              type: git
              url: https://github.com/christianrauch/libcamera.git
              version: ${{ matrix.version.libcamera }}
          EOF

      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: ${{ matrix.version.ubuntu }}
          DEB_ARCH: ${{ matrix.target_arch }}
          ROS_DISTRO: ${{ matrix.version.ros }}
          SKIP_CHECKOUT: true
          SBUILD_CONF: "$enable_network = 1;"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          PACKAGES_BRANCH: "${{ matrix.version.ubuntu }}-${{ matrix.version.ros }}-${{ matrix.target_arch }}-${{ matrix.version.libcamera }}-${{ matrix.bloom_branch }}"
