name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04
      options: --privileged
      env:
        PIP_BREAK_SYSTEM_PACKAGES: 1

    steps:
      - run: apt update

      - name: install sudo
        run: |
          apt install -y sudo

      - name: install bloom (meson)
        run: |
          apt install -y python3-pip git
          pip install git+https://github.com/christianrauch/bloom.git@meson

      - run: usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $(whoami)

      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          DEB_ARCH: arm64
          ROS_DISTRO: humble
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
